### ISSUE TITLE
How can I change the colors of the firefox tabbar? (tree-style-tab plugin)

### ISSUE THREAD

**Issue by suhaylmv** [AmadeusWM/dotfiles-hyprland#10]
![browser](https://user-images.githubusercontent.com/64747225/224481499-93463cb9-9f53-4248-8566-2bb22f417160.png)
Thanks for the awesome dots. I've used your config for firefox and tried changing the colors to the tokyonight colorscheme. I managed to change them in /chrome/config.css but couldn't find a way to do it in treestyletab plugin

**Comment by AmadeusWM** [comment]
You can change the css in: `Firefox Extensions > Tree Style Tab > Preferences > Advanced > Extra style rules for contents provided by Tree Style Tab`
![image](https://user-images.githubusercontent.com/63149896/224483411-77056e8a-b9cc-455e-855c-a4b81369750a.png)
