### ISSUE TITLE
Font problems

### ISSUE THREAD

**Issue by Rudra2002** [AmadeusWM/dotfiles-hyprland#13]
In the dependencies you instructed to install nerd-fonts-complete. But in the aur nerd-fonts-complete is unavailable so i downloaded nerd-fonts-complete-starship. But in the "eww" sidebar the Fonts are not woring. It is showing gibresh. But some times it works but when I change the selected windows I again shows gibresh. The Enthernet Icon is also broken. 

![image](https://user-images.githubusercontent.com/59008344/225138629-5f873cf8-0587-4151-9106-1083050a913f.png)

**Comment by AmadeusWM** [comment]
Thanks for posting, I will take a look at it tomorrow.
Seems like they changed the name to `nerd-fonts-complete-starship`

**Comment by AmadeusWM** [comment]
I will update the readme for that tho, thanks

**Comment by Rudra2002** [comment]
the appname is fixed but them font problem is sitll persisted. I can notsee certain fonts like "󰤟" and many others. which resulted in the gibress in the wifi. can you please check which fonts are they on.

**Comment by AmadeusWM** [comment]
Okay, thank you for the fix :D
So I've checked out the  top bar, but the icons look good to me. I've installed the `nerd-fonts-complete-starship`, but that doesn't break anything:
![image](https://user-images.githubusercontent.com/63149896/225546781-fe6b2589-a40e-425d-9175-f8d7c054f8ca.png)
I'm not sure what the problem could be tbh, these are all the font packages I have:
![image](https://user-images.githubusercontent.com/63149896/225546987-b2a1fabc-237d-4370-a829-4690cf1f0d01.png)

**Comment by Rudra2002** [comment]
can you show me your /etc/locale.conf configuration.

**Comment by AmadeusWM** [comment]
ok:
```
LANG=en_US.UTF-8
LC_ADDRESS=nl_BE.UTF-8
LC_IDENTIFICATION=nl_BE.UTF-8
LC_MEASUREMENT=nl_BE.UTF-8
LC_MONETARY=nl_BE.UTF-8
LC_NAME=nl_BE.UTF-8
LC_NUMERIC=nl_BE.UTF-8
LC_PAPER=nl_BE.UTF-8
LC_TELEPHONE=nl_BE.UTF-8
LC_TIME=nl_BE.UTF-8
```

**Comment by Rudra2002** [comment]
https://github.com/AmadeusWM/dotfiles-hyprland/commit/352f056b7dc9c95fda481bad48f689af8f98363f
 fixed :+1:
