### ISSUE TITLE
Audio is not reflected on load

### ISSUE THREAD

**Issue by MaximilianLloyd** [AmadeusWM/dotfiles-hyprland#15]
When launching. The volume tray displays a volume of -20.25dB. But when playing audio i can hear it fine. When I adjust the volume from the tray it jumps to zero and then is adjustable from there. It feels like there are two processes controlling the audio. Any suggestions for how to fix this?

**Comment by AmadeusWM** [comment]
I will take a look tomorrow, thanks for reporting. Dont know why that would happen tbh

**Comment by AmadeusWM** [comment]
I don't experience this issue.
Might've something to do with your amixer, you can try take a look at the this file:
`~/.config/hypr/themes/apatheia/eww/eww.yuck`, at lines `134` and `359`, that's where amixer is used to set the volume.

**Comment by MaximilianLloyd** [comment]
Aha, thank you very much. Could it have something to do with me using PipeWire?

**Comment by AmadeusWM** [comment]
I also use pipewire, so the problem is probably with something else. 
I have no idea what else could cause such behavior in case `amixer -D pulse sset Master 10%`  works.

**Comment by AmadeusWM** [comment]
![image](https://user-images.githubusercontent.com/63149896/227618044-6cdc1cab-15ef-4e5d-b10d-feaf6958211d.png)
btw, I use this package for `amixer`. Hope it helps !

**Comment by MaximilianLloyd** [comment]
I hadn't set up my pipewire properly. Everything wroks perfectly now! Thanks for this awesome config.
