### ISSUE TITLE
i cant remove the workspaces and luancher icons 

### ISSUE THREAD

**Issue by hexisXz** [AmadeusWM/dotfiles-hyprland#16]
how do i remove the  workspaces and luancher from the bar? i have checked in every dot file and i can't find anything.

**Comment by AmadeusWM** [comment]
im so sorry for noticing this issue so late! To remove the workspaces and the launcher from the bar go to: `~/.config/hypr/themes/apatheia/eww/eww.yuck`, and remove the `(launcher) (sep) (workspaces) at line 252: 
```lisp
(defwidget left []
  (box
    :orientation "h"
    :space-evenly false
    :halign "start"
    :class "left_modules"
;remove lines from here
    (launcher)
    (sep)
    (workspaces)
;till here
))
    ```

**Comment by AmadeusWM** [comment]
Closed due inactivity.
