### ISSUE TITLE
Firefox right click menu scrolls automatically down and stays there stuck.

### ISSUE THREAD

**Issue by haShinui** [AmadeusWM/dotfiles-hyprland#19]
So hello, I like your firefox theme a lot and I use it. 
The problem I encounter is when I right click on a tab on tst, it opens up the menu where I normally can scroll through, on the right side of the menu I have this bar I can drage open and down with a mouse click.
What happens when I open the right click menu is that it automatically scrolls down and stays stuck there. I can still use the bar on the right to drag the bar up, but the moment I let go it goes back down. 
I deinstalled reinstalled and did everything but didnt work. Also when I reset this setting, for short removed the theme it worked again like a charm. So there is some kind of problem, I tried to find the problem but didnt find anything.
Also same problem goes for when you right click on a word that you misstyped and it shows you the correction, but it cant see it because it scrolls down immediately.
I am pretty sure it has to do with the chrome dot file, because on the default firefox profile there is no problem.

Firefox version: 113.0.1(brand new, but problems were also happening in 112)
OS: Arch, Hyprland

**Comment by haShinui** [comment]
So i went through the configs and went to the popup.css and I thought at first it has something to do with the line 144 and after about the scrollbar thing on the side, but it doesnt. Maybe it also could be an DPI issue or sensitivity or snapping issue because,
I found out that if scroll up with mousebar and I dont move the mouse at all, it doesnt snap down and I can even click without the problem. I can also move the mouse a bit. BUT the moment I TOUCH another box(example, new Tab box to reload Tab), the movement happens and it snaps down. So I think the sensitivity or speed of the snapping of the different option is the problem.
Also if I dont use the mouse and instead the arrow keys same thing happens with snapping.

**Comment by AmadeusWM** [comment]
I will take a look at this when I have time, I'm quite bussy with school atm 😅. could you provide a video or picture? Im not sure what you mean by it scrolling down, I dont seem to have such an issue

**Comment by haShinui** [comment]
https://github.com/AmadeusWM/dotfiles-hyprland/assets/67230963/9f17b0ba-a9dc-4005-b336-c17f46e83644

Hello so I made a video, hopefully it will help. So what I first do was navigating menus with the mouse and you can see the moment my mouse touches the box (ex New tab) it twitches down. Also in the last menus, when I still right click on link on TST, not the grammar stuff,  I used my arrow keys instead of mouse.

**Comment by AmadeusWM** [comment]
Hello,
I've messed around a bit, and it seems to be fixed when I reenable these buttons for scrolling:
![image](https://github.com/AmadeusWM/dotfiles-hyprland/assets/63149896/f4253d87-a1cf-47a2-a41c-d8047a8f945d)
I updated the firefox theme in this repo. So if you update to the newest version, it should be fixed. 
Thanks for posting the issue, hope this helps :D

**Comment by NakedTrashPanda** [comment]
Was also experiencing a similar issue for a while, but with the bookmarks menu as well. Thought it was something to do with this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1809084), but it was still occurring after the update. Seems as if you fixed it though. Amazing work!

**Comment by AmadeusWM** [comment]
Glad to hear it's fixed now! I'll close this issue

**Comment by haShinui** [comment]
Sorry took so long to respond, was busy ricing and writing down ideas after the ricing competition. But thanks a lot that worked for me.
