### ISSUE TITLE
Black buttons on dark background

### ISSUE THREAD

**Issue by Temanor** [AmadeusWM/dotfiles-hyprland#21]
I downloaded the firefox theme on my laptop, and the buttons in the top left (back, forward, refresh) are barely visible.
I have also had inconsitencies with the + button to open a new tab, on my main computer, where the button would be black as well. I do not have this issue on my desktop however.
![Screenshot 2023-08-30 133202](https://github.com/AmadeusWM/dotfiles-hyprland/assets/91745601/06338808-ff89-4be1-ba15-1c8df211c612)

**Comment by HynDuf** [comment]
Me too. Just updated firefox yesterday and this bug appeared.

**Comment by gabeclarke** [comment]
Hi! I'm concerned this will not fix it forever, but for now try this solution. 

https://old.reddit.com/r/FirefoxCSS/comments/164ok08/v117_breaks_custom_svg_icons_no_longer_changes/

This put the buttons back to the custom svg icons that Amadeus provides in the repo.

**Comment by Temanor** [comment]
> Hi! I'm concerned this will not fix it forever, but for now try this solution.
> 
> https://old.reddit.com/r/FirefoxCSS/comments/164ok08/v117_breaks_custom_svg_icons_no_longer_changes/
> 
> This put the buttons back to the custom svg icons that Amadeus provides in the repo.

Thank you for the solution.
For now this should be good enough.

**Comment by AmadeusWM** [comment]
Thanks for the solution, I will add it to the readme :D
