### ISSUE TITLE
Latest Firefox update (v108) enlarged extensions, ruining the UI.

### ISSUE THREAD

**Issue by NakedTrashPanda** [AmadeusWM/dotfiles-hyprland#3]
![firefox_982_NsfcXTSaea](https://user-images.githubusercontent.com/29274375/207596360-de4dcb40-1938-4f60-86d9-afb5fb279fb3.png)

**Comment by AmadeusWM** [comment]
Thanks for posting the issue, that looked horrendous.
It should be patched now. Can you try it out?
![image](https://user-images.githubusercontent.com/63149896/207606180-4dcce55e-f4b3-4d4f-afa2-733ee01fefba.png)

**Comment by NakedTrashPanda** [comment]
Working as intended, thank you very much for the quick fix! :)
