### ISSUE TITLE
Private window Window-control-buttons

### ISSUE THREAD

**Issue by AlexMe2** [AmadeusWM/dotfiles-hyprland#4]
Hello again, this time i have an issue on linux with private browsing, there are no window control buttons on it, it just says "private" as in the attached picture, also, the extensions buttons seems to be a bit "wide" on normal or private, anything i can modify to fix it? thanks
![image](https://user-images.githubusercontent.com/36035544/208234281-a3524a10-6b7c-4a71-be7f-a2bcc0c36f3c.png)
![image](https://user-images.githubusercontent.com/36035544/208234318-032fc936-9c63-4a40-b7c4-087e3e3421da.png)

**Comment by AmadeusWM** [comment]
Hi, this might be because of the new Firefox update, have you tried reinstalling the theme? (replacing the `chrome` folder again)
I can't reproduce the wide extension buttons.
![image](https://user-images.githubusercontent.com/63149896/208234759-5d670d26-8a8a-4b25-a213-96b4cc7f059d.png)

**Comment by AmadeusWM** [comment]
Okay, the hidden window control buttons were messed up because of the "browsing" text. I just removed it, can you try the newest commit? Also, you'll have to patch it again for windows, as in the previous issue :D thanks

**Comment by AlexMe2** [comment]
> Hi, this might be because of the new Firefox update, have you tried reinstalling the theme? (replacing the `chrome` folder again) I can't reproduce the wide extension buttons. ![image](https://user-images.githubusercontent.com/63149896/208234759-5d670d26-8a8a-4b25-a213-96b4cc7f059d.png)

the wide buttons got fixed by re-applying the theme, but now after the latest commit there are no window control buttons again xD

**Comment by AlexMe2** [comment]
so doing the windows fix, worked on linux as well
but there is a weird padding in the buttons now
![image](https://user-images.githubusercontent.com/36035544/208235903-b62d8c70-b21d-4a66-a3ec-1cdfb5ff995b.png)
which i fixed by modifying the  

:root:not([inFullscreen]) toolbar#nav-bar {
    margin-left: 0 !important;
    margin-right: calc(var(--wc-left-space) * 2 + 60px) !important;
}

from wc-without-tabline-r.css to 

:root:not([inFullscreen]) toolbar#nav-bar {
    margin-left: 0 !important;
    margin-right: calc(var(--wc-left-space) * 2 + 65px) !important;
}
![image](https://user-images.githubusercontent.com/36035544/208235945-04675154-8cd3-418f-844a-0a197d9f9318.png)
so, thanks for the help, again :D

**Comment by AmadeusWM** [comment]
Oh okay, thanks! I will add it to the css right away.
