### ISSUE TITLE
Window title not showing up properly

### ISSUE THREAD

**Issue by ghost** [AmadeusWM/dotfiles-hyprland#9]
![swappy-20230224_224615](https://user-images.githubusercontent.com/87923259/221244791-609fd98a-0259-492d-893f-d70437411159.png)
![swappy-20230224_224643](https://user-images.githubusercontent.com/87923259/221244800-501f7c49-0b14-4e9b-9f3f-f1174e727383.png)

# Steps to reproduce

Just open any application and it will happen. One peculiarity I noticed is when I switched tabs on librewolf it fixed it self and showed the correct title but as soon as I unfocused and refocused librewolf it happens again...

**Comment by AmadeusWM** [comment]
Thank you for posting the issue, I will look into it as soon as I have time :D

**Comment by kopp4** [comment]
Hyprland has a activewindow v2 rule
https://raw.githubusercontent.com/kopp4/dotfiles-hyprland/main/themes/apatheia/eww/scripts/appname
This one might work for you.

**Comment by ghost** [comment]
> Hyprland has a activewindow v2 rule https://raw.githubusercontent.com/kopp4/dotfiles-hyprland/main/themes/apatheia/eww/scripts/appname This one might work for you.

YES! This fixed the issue.
Thank you very much!
